name: "Preevy CLI"
description: "Runs the Preevy CLI"
author: "Livecycle"
inputs:
  profile-url:
    required: true
    description: "The Preevy profile URL"
  command:
    required: true
    description: "The Preevy command to run."
  args:
    required: false
    description: "Additional args to provide to the preevy CLI."
outputs:
  preview-environments-urls:
    description: "The generated URLs of the preview environments create by Preevy"
    value: ${{ steps.run_preevy.outputs.urls_table }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install the Preevy CLI
      shell: bash
      run: npm i -g preevy
    - name: Initialize Preevy
      shell: bash
      run: preevy init --from ${{ inputs.profile-url }}
    - name: Run Preevy
      shell: bash
      id: run_preevy
      run: |
        preevy ${{ inputs.command }} ${{ inputs.args }}
        cat << EOF > urls.txt
        | Service | Port | URL |
        |---------|------|-----|
        $(preevy urls --json | jq -r '.[] | {service, port, url} | join(" | ") | "| " + . + " |" ')
        EOF
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "urls_table<<$EOF" >> $GITHUB_ENV
        cat urls.txt >> $GITHUB_ENV
        echo "$EOF" >> $GITHUB_ENV
